name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: npm install
      - run: npx nuxt build --preset github_pages

      # Clean and prepare the public directory
      - name: Clean and prepare public directory
        run: |
          # Create a fresh temporary directory
          mkdir -p ./temp-public
          # Copy files to temp directory, following symlinks
          cp -rL .output/public/* ./temp-public/
          # Remove the original public directory
          rm -rf .output/public
          # Move the temp directory to be the new public directory
          mv ./temp-public .output/public
          # Show directory contents and size
          du -hs .output/public
          echo "Listing all files in public directory:"
          ls -la .output/public

      # Ensure GitHub Pages compatibility
      - run: touch .output/public/.nojekyll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .output/public
          if-no-files-found: error

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
