name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: npm install
      - run: npx nuxt generate  # Ensure fully static output

      # Check if output directory contains only valid static files
      - name: List files in output directory
        run: ls -lah .output/public

      # Ensure no symlinks
      - name: Check for symlinks
        run: find .output/public -type l -ls

      - name: Remove symlinks
        run: find .output/public -type l -exec rm -f {} \;

      # Ensure GitHub Pages compatibility
      - run: touch .output/public/.nojekyll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          include-hidden-files: true
          path: .output/public  # Ensure only static files are uploaded

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
